apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: frontend-availability
  namespace: opentelemetry-demo
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  service: frontend
  slos:
    - name: availability
      objective: 99.5
      description: Frontend HTTP success rate over 30d
      sli:
        # Use spanmetrics emitted by the Collector to ensure data exists without app-specific metrics.
        # Error budget based on span status code.
        events:
          errorQuery: |
            sum(rate(traces_span_metrics_calls_total{service_name="frontend", status_code="STATUS_CODE_ERROR"}[{{.window}}]))
          totalQuery: |
            sum(rate(traces_span_metrics_calls_total{service_name="frontend"}[{{.window}}]))
      alerting:
        name: FrontendAvailability
        labels:
          category: availability
        annotations:
          summary: "Frontend availability SLO is burning error budget"
